### ISSUE TITLE
Expand Matches for Ticket References

### ISSUE THREAD

**Issue by kpollich** [scottgonzalez/changelogplease#11]
https://help.github.com/articles/closing-issues-via-commit-messages/

JIRA references are currently only generated from strings matching 'Fixes {ticketref}'. Could that be expanded to include some more terminology?

**Comment by scottgonzalez** [comment]
I started implementing this, but then I remembered why changelog please doesn't handle these (thanks unit tests!). We use "fixes" to identify issues and "closes" to identify PRs. Since we don't want to include the PRs, but rather the commits and issues, we avoid looking for "closes".

I could see this becoming an option, but there's some refactoring required to make that possible. Since I know that you wouldn't actually use the new feature right now, I'm going to close this. For posterity, I've included my changes below. To add an option, we'd need to expose a list of words that can be turned on/off and then generate the regex per instance based on those options. This would likely require making the ticket parsers contains objects so the partial regex can be pulled out to generate the full regex within the changelog instance.

``` diff
diff --git a/index.js b/index.js
index 992cd50..1aff7e4 100644
--- a/index.js
+++ b/index.js
@@ -3,6 +3,8 @@ var Repo = require( "git-tools" );
 exports = module.exports = changelog;
 exports.Changelog = Changelog;

+var referenceKeywords = /(?:[Ff]ix(?:e[ds])?|[Cc]lose(?:[ds])?|[Rr]esolve(?:[ds])?)/.source;
+
 function changelog( options, callback ) {
    var instance = new Changelog( options );

@@ -41,13 +43,19 @@ function Changelog( options ) {
    }
 }

+Changelog.createTicketParserRegex = function( regex ) {
+   return new RegExp( referenceKeywords + " " + regex.source, "g" );
+};
+
 Changelog.ticketParsers = {
    github: function ( commit, ticketUrl ) {
        var tickets = [];

        // Sane global exec with iteration over matches
        commit.replace(
-           /Fix(?:e[sd])? ((?:[a-zA-Z0-9_-]{1,39}\/[a-zA-Z0-9_-]{1,100}#)|#|gh-)(\d+)/g,
+           Changelog.createTicketParserRegex(
+               /((?:[a-zA-Z0-9_-]{1,39}\/[a-zA-Z0-9_-]{1,100}#)|#|gh-)(\d+)/
+           ),
            function ( match, refType, ticketId ) {
                var ticketRef = {
                    url: ticketUrl( ticketId ),
@@ -73,7 +81,7 @@ Changelog.ticketParsers = {

        // Sane global exec with iteration over matches
        commit.replace(
-           /Fix(?:e[sd])? ([A-Z][A-Z0-9_]+-\d+)/g,
+           Changelog.createTicketParserRegex( /([A-Z][A-Z0-9_]+-\d+)/ ),
            function ( match, ticketId ) {
                var ticketRef = {
                    url: ticketUrl( ticketId ),
```
