### ISSUE TITLE
Add support for other issue trackers

### ISSUE THREAD

**Issue by gseguin** [scottgonzalez/changelogplease#7]
Externalizing the parseCommit regex into a static variable of Changelog would allow to support other ticket formats. I'm trying to use changelogplease against JIRA issues.

PR will follow.

**Comment by scottgonzalez** [comment]
I'm hesitant to expose just the regex since it's so closely tied to the replacement function. Maybe we should just expose many parsers and let the user choose which ones they want to use (including adding their own). I'm fine with bundling a JIRA parser though. This approach would also get away from the slightly hacky hard-coding of GitHub issue URLs when there's a similar `ticketUrl` option.

**Comment by gseguin** [comment]
So something like passing in an ```issueTracker``` property to the options and default that to ```github``` ?
